---
- name: Install required software
  apt: pkg={{ item }} state=latest
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
  tags: mailcatcher

- name: Install rubygems
  apt: pkg=rubygems-integration state=latest
  tags: mailcatcher

- name: Install Mailcatcher
  command: gem install mailcatcher
  tags: mailcatcher

- name: Create startup script for mailcatcher
  template: src=etc--init.d--mailcatcher.j2 dest=/etc/init.d/mailcatcher mode=0755
  tags: mailcatcher

- name: Mailcatcher will start upon boot
  command: update-rc.d mailcatcher defaults
  tags: mailcatcher

- name: Make sure Mailcatcher is not running
  command: pkill mailcatcher
  ignore_errors: yes
  tags: mailcatcher

- name: Start mailcatcher properly with the start script
  command: /etc/init.d/mailcatcher
  tags: mailcatcher
